spring:
  profiles: local-mssql
  datasource:
    url: jdbc:postgresql://localhost/postgres?user=postgres&password=root&ssl=false
    username: postgres
    password: root
    dbcp:
      max-active: 5
    tomcat:
      max-active: 5
 
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  http:
    multipart:
      max-request-size: 10Mb
---
spring:
  datasource:
    url:
      jdbc:postgresql://localhost/postgres?user=postgres&password=root&ssl=false 
