spring:
  jpa:
    show-sql: true
    properties:
      hibernate.dialect:
          org.hibernate.dialect.MySQLDialect
   
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&user=root&password=root
---
logging:
  level:
    root: warn        
              